# Generated by Django 4.2.7 on 2025-11-21 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['isim'],
            },
        ),
        migrations.CreateModel(
            name='Haber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Haber Başlığı')),
                ('icerik', models.TextField(verbose_name='Haber İçeriği')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='haber_resimleri/', verbose_name='Haber Resmi')),
                ('olusturma_tarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('yayinda', models.BooleanField(default=True, verbose_name='Yayında mı?')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haberler', to=settings.AUTH_USER_MODEL, verbose_name='Editör')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haberler', to='haberler.kategori', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Haber',
                'verbose_name_plural': 'Haberler',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
    ]
