# Generated by Django on 2025-11-21

from django.db import migrations
from django.contrib.auth.hashers import make_password


def admin_kullanici_olustur(apps, schema_editor):
    """
    Admin kullanıcısını otomatik olarak oluşturur.
    Kullanıcı adı: admin
    Şifre: admin123
    """
    User = apps.get_model('auth', 'User')
    
    # Eğer admin kullanıcısı yoksa oluştur
    if not User.objects.filter(username='admin').exists():
        User.objects.create(
            username='admin',
            email='admin@haberler.com',
            password=make_password('admin123'),  # Şifre: admin123
            is_staff=True,
            is_superuser=True,
            is_active=True,
            first_name='Admin',
            last_name='Kullanıcı'
        )


def admin_kullanici_sil(apps, schema_editor):
    """
    Migration geri alınırsa admin kullanıcısını siler.
    """
    User = apps.get_model('auth', 'User')
    User.objects.filter(username='admin').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(admin_kullanici_olustur, admin_kullanici_sil),
    ]

